cargo = [
  "bandwhich",
  "cargo-make",
  "eza",
  "flamegraph",
  "git-delta",
  "hexyl",
  "cargo-binstall",
  "hyperfine",
]

brew = [
  "brotli",
  "cloudflared",
  "ncdu",
  "scrcpy",
  "socat",
  "tig",
  "tmux",
  "tree",
  "yazi",
]
